channels:
  - defaults
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - h5py
  - matplotlib
  - pandas
  - pip
  - python==3.8.*
  - omero-py
  - openjdk
  - conda-forge::wxpython==4.1.0
  - imageio
  - inflect
  - Jinja2
  - mahotas
  - scikit-image
  - scikit-learn
  - scipy
  - six
  - pip:
    - ome-zarr
    - numpy
    - git+https://github.com/CellProfiler/CellProfiler.git@v4.1.3
